name = "Runic Create"
author = "Ansuz"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b584e282ad8c999d50691576c7b7c078d4d60459c869aef3fa283e687951c31d"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
