name = "Runic"
author = "Ansuz"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "183b540022cdb4d69acb3106b71a6e2bf45cc484ea408ef10aa94a24c2a48421"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
