name = "Runic"
author = "Ansuz"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7abc5509033bb79cfb6ff72799a96e4a4b2e2bc52a5dac192cdcaa9649d5f32c"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
