name = "Runic"
author = "Ansuz"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa537521d1c6c918bddefe6ca4756802b2d30316b1e3530a2bdec9f9929e70f8"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
