name = "Runic Create"
author = "Ansuz"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9a3109984a5fcae5d964ffd7824ca4da79ff2807b4fd6c3d277d2c53f526c22"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
