name = "Runic Create"
author = "Ansuz"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7748ec914a3fac486050cccac135c94403ed8c5314c65f05bb1917bf4c80f026"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
